### ISSUE TITLE
vSphere VM Template not found 

### ISSUE THREAD

**Issue by marekmrowca** [chef-partners/chef-provisioning-vsphere#93]
### Versions:
* Version of Chef-Provisioning: 2.7.0
* Version of Chef-Provisioning-vSphere: 2.3.1

### Platform Details
* Version of vSphere/vCenter:  6.5.0.13000
* Version of ESXi: VMware ESXi, 6.5.0, 8294253

### Scenario:
I want to create a VM from a template, bootstrap it to Chef server and run a cookbook on it.

### Steps to Reproduce:
Below is the excerpt from my .kitchen.yml. I tried different "resource_pool" entries.

```
driver:
  name: vsphere
  driver_options:
    host: 192.168.0.10
    user: terraform
    password: ***
    insecure: true
  machine_options:
    start_timeout: 600
    create_timeout: 600
    ready_timeout: 90
    bootstrap_options:
      use_linked_clone: true
      datacenter: 'Datacenter'
      template_name: 'CM_TMPL_TF_W10Pro1709x64_Symantec'
      vm_folder: 'Terraform'
      num_cpus: 2,
      network_name:
        - '415-SDE-Virtual'
      memory_mb: 4096
      resource_pool: 'vSAN_Tier2' 
      ssh:
        user: admin
        password: ***
        elevated: true
        port: 5985
...
platforms:
 - name: Win2012x64
suites:
  - name: default
    run_list:
      - recipe[m4::default]
```

### Expected Result:
VM is created from a template on vCenter as a first step.

### Actual Result:

```
-----> Starting Kitchen (v1.20.0)
-----> Cleaning up any prior instances of <default-Win2012x64>
-----> Destroying <default-Win2012x64>...
       Finished destroying <default-Win2012x64> (0m0.00s).
-----> Testing <default-Win2012x64>
-----> Creating <default-Win2012x64>...
[2018-10-31T16:11:15+01:00] WARN: No cookbooks directory found at or above current directory.  Assuming /root/gitlab-runner/builds/6567bb15/0/gitlab/Cookbooks/m4.
creating machine default-Win2012x64-922ba976 on vsphere://192.168.0.10/sdk?use_ssl=true&insecure=true
  datacenter: "Datacenter"
  template_name: "CM_TMPL_TF_W10Pro1709x64_Symantec"
  vm_folder: "Terraform"
  num_cpus: 2
  network_name: ["415-SDE-Virtual"]
  memory_mb: 4096
  ssh: {:user=>"terraform", :password=>"*********", :elevated=>true, :port=>5985}
establishing connection to 192.168.0.10
create node default-Win2012x64-922ba976 at chefzero://localhost:1
  add normal.chef_provisioning = {}
  add normal.tags = nil
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [vSphere VM Template not found [/CM_TMPL_TF_W10Pro1709x64_Symantec]] on default-Win2012x64
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

I would appreciate any help in the subject.
Best regards,
Marek
